### ISSUE TITLE
Question: Why return value of onBeforeSignIn is limited to string?

### ISSUE THREAD

**Issue by savbace** [bjerkio/oidc-react#1020]
I'm curious why return type of [onBeforeSignIn](https://github.com/bjerkio/oidc-react/blob/bc69de01fa9cfa431c5c979e8f18746832db7b3e/src/AuthContextInterface.ts#L136) is limited to `string`?
```ts
onBeforeSignIn?: () => string;
```
Original [SigninState.data](https://github.com/authts/oidc-client-ts/blob/4c60d9311e50880b4bb54c9ebf4251ae49abbb52/src/SigninState.ts#L37C9-L37C23) has `unknown` type which basically means that we can put anything [JSON-serializable](https://github.com/authts/oidc-client-ts/blob/4c60d9311e50880b4bb54c9ebf4251ae49abbb52/src/SigninState.ts#L77) in the state.

Thanks for answers!

**Comment by simenandre** [comment]
Hello,

Thank you for posting this issue. You're referring to what `oidc-client-ts` are using; however, most of our concepts come from `oidc-client-js`.

The reason why it is set to `string` is basically because it's passed as `state`. See: https://github.com/bjerkio/oidc-react/pull/910

In not too deep into this anymore, so could you help me understand better what you use-cases are? Are you willing to open a PR? :)

**Comment by savbace** [comment]
@simenandre 
Sorry, have no time to reply before. Posted simple PR outlining my intentions: https://github.com/bjerkio/oidc-react/pull/1021.

**Comment by savbace** [comment]
Closing. It was completed in #1021.
