### ISSUE TITLE
Any plans for SSR support?

### ISSUE THREAD

**Issue by daniel-ac-martin** [bjerkio/oidc-react#329]
This looks like a really neat, simply library but it would appear not to support SSR.

Are there any plans to change that? Would it be a lot of work to implement?

**Comment by cobraz** [comment]
Hello Daniel,

I've done some testing on this before. I don't personally do a lot of SSR development, so I don't know what needs to be added in order to support it. Maybe @ryancole does?

I were able to use the `oidc-react` in my testing before: https://github.com/cobraz/nextjs-oidc-react

Don't remember how it was, but you can clone that and check it? :)

Btw, if you know, you are more than welcome to point out what needs to be added.

**Comment by ryancole** [comment]
@daniel-ac-martin Hmm. I've not used SSR in a few years. SSR mostly depends on browser state, which needs to somehow make it to the server to be rendered. I'm not sure in the case of OAuth that any state exists in that regard? It's all redirects and local storage stuff. But I supposed regarding local storage, the server would be rendering the JS prior to the browser has a chance to load local storage at all.

I don't personally know. I'd be curious to see how it functions.

My guess? It probably won't work as you expect it initially, but it'll just end up redirecting due to failed authentication anyway.

I don't have anything setup to test it quickly, though.

**Comment by cobraz** [comment]
I'm going to close this for now. We probably would like to look into this again after #652

**Comment by douglasg14b** [comment]
So, this is completed, or such support (or workarounds) are unavailable? I'm not following why it's closed 🤔
