### ISSUE TITLE
Accessing state after signin

### ISSUE THREAD

**Issue by ed-sparkes** [bjerkio/oidc-react#447]
I am sending some state with my signin request as wish to access it again once the signin is complete 

```typescrpt
export const SimpleLogin: React.FC = (): JSX.Element => {
  const auth = useAuth();
  
  return (
    
      <div>
        {auth?.userData && (
         <>{auth?.userData.profile.name || ''}</>
        )}
        {!auth?.userData && (
          <button onClick={() => auth?.signIn({ state: { targetUrl: window.location.pathname } })}>
            Login
          </button>
        )}
      </div>
  );
};
```

i need to access this state after login so that i can redirect to the correct path in my application, however state is undefined on the User object in the onSignIn event 

```typescrpt
<AuthProvider
      authority='someAuthority'
      clientId='someclientid'
      automaticSilentRenew
      responseType="code"
      autoSignIn={false}
      onSignIn={(user) => {
        console.log(user.state);
         // user.state is undefined
      }}
      scope="openid profile email "
      redirectUri={window.location.origin}
    >
      <RestOfMyApp />
    </AuthProvider>
```
How can i get access to the state after signin. I can see that the state is being included in the query paramaters along with the code on the redirect url, but cant work out how to access it, any help would be greatly welcomed

I noticed #36 allows the state to be sent to the authorizer server so presume it is getting through? Bu then not accessible when try to access onSignIn? @johnkors  @cobraz  any thoughts?

thanks, Ed

**Comment by cobraz** [comment]
Hello @ed-sparkes!

Thanks for using oidc-react. That's an interesting question, as oidc-react handles the callback action here:

https://github.com/bjerkio/oidc-react/blob/cbc1204b0b2f075d3d89761faa6187932dd5066a/src/AuthContext.tsx#L87-L92

We don't currently have a way for you to get `state`. However, it would be pretty trivial to get it. A simple addition to line 88 where the `state` is returned to our `onSignIn` handler would probably do it. Mind you, we are looking into improving the how we handle _callback-ing_ in #313. I haven't personally had the chance to look into that yet, so feel free to contribute! Would love to get a pull request, feedback or otherwise! If you feel like creating a simple PR to fix this particular issue, I wouldn't mind that either :)

**Comment by johnkors** [comment]
Agree, @ed-sparkes . Re: #36 . The solution didn't end up adding much value, since it didn't include getting the state _back_ after sign-in. I guess I forgot to add that comment to #36 😅 ..

**Comment by ed-sparkes** [comment]
Ok i raised a PR with the following change. Seemed unnecessary to call getUser when the signincCallback contains the user so i removed that, if there is some reason why this was being done please let me know

```
if (hasCodeInUrl(location)) {
        const userAfterSignIn = await userManager.signinCallback();
        setUserData(userAfterSignIn);
        onSignIn && onSignIn(userAfterSignIn);
        return;
      }
```
