### ISSUE TITLE
Client authentication failed: The client is not registered for the requested authentication method:

### ISSUE THREAD

**Issue by xepanunty** [bjerkio/oidc-react#697]
rror: "invalid_client"
error_description: "Client authentication failed: The client is not registered for the requested authentication method: 'client_secret_post'"

In my case is  "client_secret_jwt"

i pass :   clientAuthentication : "client_secret_jwt"
or   client_authentication : "client_secret_jwt"

looks not dynamic. 

any help?

**Comment by pseudoramble** [comment]
Hi there! The error sounds like it's coming from the back end. So oidc-react is most likely not the culprit with this particular problem.

It sounds like errors I've seen from OIDC services when I have a misconfigured client. This error is saying the client does not accept secrets sent via POST. Possible client_authentication options I've heard of are "client_secret_basic" and "client_secret_post". I would double check your OIDC service client configuration to see if something is off there.

Hope that helps!

**Comment by xepanunty** [comment]
Hi Again, Thx for your reply 

My config

const oidcConfig = {
  onSignIn: async (user: any) => {
    alert('You just signed in, congratz! Check out the console!');
    console.log(user);
    window.location.hash = '';
  },
  authority: '.well-known/openid-configuration',
  clientId:'xxxx',
  responseType: 'code',
  redirectUri: 'xxxx',
};

My question 
my service is configured to use  "token_endpoint_auth_method" : "client_secret_jwt"

But in the client "oidc-client" is by defaut : 
const DefaultClientAuthentication = "client_secret_post" // The default value must be client_secret_basic, as explained in https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication

What the parameter i need to pass in my configuration to pass the good value i needed "client_authentication" ?

client_authentication : "client_secret_jwt" ?

Thanks

**Comment by pseudoramble** [comment]
Got it - thanks for clarifying. I have not tried this out, but from looking through the oidc-client code it looks like you _might_ be able to set it by using a custom built `UserManager` object. You can do that like so with oidc-react:

```
<AuthProvider userManager={new UserManager({ /* include the rest of your oidc-config here */, client_authentication: 'client_secret_jwt' })}>...</AuthProvider>
```

The reason that might work is because in the oidc-client code the UserManager settings provided there are used to construct the TokenClient, which accepts that as a parameter. Again, not entirely positive about this since I haven't tried it directly, but I would start there.

**Comment by xepanunty** [comment]
Thank you, i will try,

**Comment by xepanunty** [comment]
Doug Swain, 

I have another question for you 

Normally the endpoint userinfo_endpoint need to be like that but in my case is  "clientinfo_endpoint": "https://xxxxxx/oauth2/clientinfo", in my cas/oauth2/.well-known/openid-configuration what i need to do? For example for solve the previous problem i ask to change  my registation app client_secret_jwt to client_secret_post, but now i have this problem and without that i cannot using your package in the good away. Any ideia?

Marcelo

**Comment by pseudoramble** [comment]
I'm not sure I understand.

Are you saying that in the response from /.well-known/openid-configuration instead of `'userinfo_endpoint': '...'` you're actually expecting `'clientinfo_endpoint': '...'` but it represents the same thing? If that is what you mean, that most likely won't be supported by even `oidc-client`. It assumes the underlying metadata will contain a key with `userinfo_endpoint` which is in the OIDC spec as recommended. The spec doesn't seem to mention `clientinfo_endpoint` as an alternative either. See here for the spec: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata.

Or maybe you're saying you need to get additional metadata from that response and it happens to be called `clientinfo_endpoint` but it's actually unrelated to `userinfo_endpoint`? If that's the case, you can try and examine the metadata through oidc-react directly, sort of like this:

```
const auth = useAuth(); // the oidc-react hook, of course
console.info(auth?.userManager?.metadata); // this may have the `clientinfo_endpoint` you'd be looking for
```

Hope that helps.

**Comment by xepanunty** [comment]
Thank you for your information's helps me a lot.

**Comment by xepanunty** [comment]
Ok, thank you, i have another question, /
oidc-react -> the is just for client frontend side, but the sessions need to manage on server side correct?

**Comment by pseudoramble** [comment]
That's correct. IdentityServer4 is an option to check out if you need a new option, though any OIDC-compatible provider should work I believe.

I would suggest closing this issue since this isn't related to oidc-react anymore. :)
