### ISSUE TITLE
clientSecret -> sent in config

### ISSUE THREAD

**Issue by xepanunty** [bjerkio/oidc-react#713]
clientSecret: configuration.client_secret,

Hi again, 
for my service works i need to sent the clientSecrete in /oauth2/token/introspect call.

I know this is unsecure if I sent this from the client. 
 oidcConfig = {
      onSignIn: async (user: any) => {
        window.location.href = "xxxxxx"
      },
      authority: configuration.authority,
      clientId: configuration.client_id,
      clientSecret: configuration.client_secret, -> EXISTS ANOTHER WAY TO SET THAT?
      responseType: configuration.response_types[0],
      redirectUri: configuration.redirect_uris[0],
      loadUserInfo: false, // not exists endpoint
      revokeAccessTokenOnSignout: true

My question, exists another way for I set this parameter?

**Comment by cobraz** [comment]
Client secrets should never be stored in `oidc-react` (since it would make it available publicly).

However, if you use PKCE flow, you can code exchange without the secret. The introspect call should normally only be done by the backend, so I'm not sure why you want to this here? Am I missing something?
