### ISSUE TITLE
Migrate to oidc-client-ts

### ISSUE THREAD

**Issue by miestr** [bjerkio/oidc-react#859]
Since oidc-client library is no longer maintained and its official successor is oidc-client-ts, would it be possible to update the dependency? The oidc-client does not have any newest bugfixes or new type definitions that are already present in oidc-client-ts

**Comment by miestr** [comment]
I opened a [pull request 860](https://github.com/bjerkio/oidc-react/pull/860)

**Comment by cobraz** [comment]
Hey, thanks for this! I haven't been around the block lately, but how is `oidc-client-ts` the official successor?

Is it because it's been the one most active/used? As I stated in #652, I was unsure about the longevity of `oidc-client-ts`. Now, almost a year later, I am sure it's a nice option for `oidc-react`. At least it's the easiest :)

So, again, thanks!

**Comment by cobraz** [comment]
Btw, I'm closing this as this all belongs in #652. 👍
