### ISSUE TITLE
Bug with reactStrictMode (<StrictMode/>)

### ISSUE THREAD

**Issue by AlexanderKositsyn** [bjerkio/oidc-react#901]
React calls useEffect [this one](https://github.com/bjerkio/oidc-react/blob/main/src/AuthContext.tsx#L105) twice in strictMode. It results in error `No matching state found in storage`.  I found a solution to fix this by disabling this mode. I work with nextjs so I just remove `reactStrictMode: true` from `next.config.js`. So I decided to create issue for people who will get this bug 😄

**Comment by bdekok** [comment]
I've noticed the same thing in my project

**Comment by mathieu-fournier** [comment]
Disabling strict mode is not recommended because, without it, you won't benefit from it's warning about side effects and more. 
Instead, it might be better to put the strict mode node after the authentication component. So at least, everything under the auth component will benefit from stric mode. 

Ex : 
...
<Authentication>
     <StrictMode>   <---- below the auth
         <other stuff/>
       </StrictMode>
</Authentication>

The best would be that the second re-render is supported by the lib tho.

**Comment by wutzebaer** [comment]
I have a problem with that too. The second trigger interrupts sometimes (race condition) the first redirect what leads to an error in firefox.

Putting AuthProvider outside of StrictMode is a problem, because AuthProvider must be inside BrowserRouter to redirect after login, but idk, if it is an problem if BrowserRouter is outside of StrictMode

**Comment by mathieu-fournier** [comment]
@wutzebaer 

StricMode is a development tool that warns us about possible unwanted side-effect and other common issues that happens in react.
So to answer your question, it's up to you to decide if it's a problem of not. 
https://reactjs.org/docs/strict-mode.html

In my opinion, it;s not a problem if BrowserRouter is outside of strict mode. 
Since routing usually happens only once. 

Hope it helps (:

**Comment by cardano-tools-nft** [comment]
@mathieu-fournier thank you for clarification

**Comment by jamesdh** [comment]
This should be fixed by #962
