### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by jamesdh** [bjerkio/oidc-react#934]
Links in docs that reference source code point to a repository under user account "pamapa", not "bjerkio", and that repository does not exist, hence a GitHub 404 page is shown.

**Comment by cobraz** [comment]
Hello 👋 

I couldn't find any dead links in our README. Where is this issue? Can you share? :)

**Comment by jamesdh** [comment]
https://github.com/bjerkio/oidc-react/blob/main/docs/modules/authcontext.md

Look at the link for `Defined in: src/AuthContext.tsx`

Or just checkout main and do a search for pamapa, there are 40 difference instances of it in broken links.

**Comment by jamesdh** [comment]
Also, I was not able to run typedoc or typedoc-plugin-markdown locally, so I updated them to their latest versions which got them working but it dramatically changes the doc output. Looks like some changes are needed for the doc generation to work correctly w/ their latest releases.

**Comment by jamesdh** [comment]
The doc generation should probably be part of the GitHub Action workflow on release. I see numerous PR's where the docs were not updated despite the PR changing the API. 

I'm guessing the links are broken because someone ran the doc generation in a forked branch, PR'd it, and then the PR was merged without proper review.

**Comment by cobraz** [comment]
You are probably right, we should maybe do that on `main` on a `push` event.

There's already a daily GitHub Action workflow that are currently failing to generate documentation.
Maybe you wanna take a look at fixing it? I would love to see a PR on this.

If not, I'll probably look into it once I'm back on my feet. Currently out sick! Might be @braaar can take a look as well :)

**Comment by cobraz** [comment]
#928 is relevant here :)

**Comment by cobraz** [comment]
Hello @jamesdh!

Thank you so much for your contributions! I tried to reach out to you through email, but it didn't work.
As you have seen, I've invited you as a collaborator to our repository. This is because for an open-source project to thrive, we need to build a community, not just a library. 😄

We have a Discord server, [Bjerk & Friends](https://discord.gg/SXMpgmPq5F), which initially was intended for game nights, but recently found it's incredible to keep in touch with our friends and others in the community. Feel free to join us!

I hope you'll feel welcome in our little community!
